
use_default_settings: true

general:
  debug: false
  instance_name: "Shiraali Search"
  enable_metrics: false

search:
  formats:
    - html
    - json

server:
  secret_key: "TEMPORARY-KEY-REPLACED-BY-ENV"
  limiter: false
  public_instance: false
  bind_address: "0.0.0.0"
  default_http_headers:
    Access-Control-Allow-Origin: "https://shiraali.ir"

engines:
  - name: ecosia
    engine: xpath
    disabled: false
    shortcut: eco
    categories: [general]
    timeout: 10.0
    search_url: https://www.ecosia.org/search?q={query}
    results_xpath: //div[@class="result"]
    title_xpath: .//a[@class="result-title"]
    url_xpath: .//a[@class="result-title"]/@href
    content_xpath: .//p

  - name: dogpile
    disabled: false
    inactive: false
    shortcut: dog
    dogpile_categ: search
    categories: [general]
    timeout: 8.0
